deltaDAO/mvg-portal

package.json, src/components/organisms/AssetActions/Compute/index.tsx, src/components/organisms/AssetActions/Edit/DebugEditAdvancedSettings.tsx, src/components/organisms/AssetActions/Edit/EditAdvancedSettings.tsx, src/components/pages/Profile/History/ComputeJobs/Details.tsx, src/components/pages/Profile/History/ComputeJobs/Results.module.css, src/components/pages/Profile/History/ComputeJobs/Results.tsx, src/hooks/useConsume.ts, src/models/FormEditCredential.ts, src/utils/compute.ts
Fixes #35 
- update ocean.js
- update compute history (especially `Results.tsx`)
- refactoring
see also: https://github.com/oceanprotocol/market/pull/958
=> Ffix: Update compute history to reflect v3 changes

src/components/atoms/Input/InputGroup.module.css, src/components/molecules/FormFields/URLInput/Input.tsx
Fixes #89 
- avoid running url sanitization during metadata editing if sample file field is empty
- "add file" button is now same height as the input field
=> Fix: edit metadata crash

src/components/organisms/AssetActions/Compute/index.tsx, src/components/organisms/AssetContent/AlgorithmDatasetsListForCompute.tsx, src/components/templates/Search/index.tsx, src/utils/aquarius.ts
Fixes #67 
- replace "term" with "match_phrase" in `getAlgorithmDatasetsForCompute` base query
- hide algorithms with different service endpoint than dataset in ctd asset actions
=> Fix: query for algo's compatible datasets

src/components/molecules/InteractiveModalImage.module.css
Fixes #104 
- image doesn't overflow anymore from the modal window
- adjust close button size to be visible on all screen sizes
=> Fix: modal close button size

src/components/molecules/FormFields/FilesInput/index.tsx
- add a specific error message when the download of a service SD from the provided URL fails
=> fix: fail get service SD error message

src/components/pages/Home.tsx, src/providers/Web3.tsx
- move featured assets list higher on the homepage
- hide the onboarding section if the user already has both GX and OCEAN tokens
=> enhancement: move featured assets and hide onboarding section

src/components/atoms/Publisher/index.module.css, src/components/atoms/Publisher/index.tsx, src/components/atoms/VerifiedBadge.module.css, src/components/atoms/VerifiedBadge.tsx, src/components/atoms/VerifiedPublisher.tsx, src/components/molecules/FormFields/URLInput/Input.tsx, src/components/organisms/AssetContent/MetaMain.tsx, src/providers/Asset.tsx, src/utils/metadata.ts
- show provider name from a verified SD (if available) in asset details
- detach metadata loading from service SD verification in asset details page
=> feat: add verified service provider name to asset details page

src/components/templates/Search/utils.ts
Fixes #
- revert change to `_id` for search queries
=> fix: change search on fields back to 'id'

src/providers/Ocean.tsx
Fixes #194 
- adjust default timeout value for ocean.js http requests to 10s
=> fix: change default timeout for oceanjs to 10s

content/pages/privacy/policies.json, src/components/molecules/PrivacyHeader.tsx, src/hooks/usePrivacyMetadata.ts, tests/unit/__fixtures__/privacyMetadata.json
- remove dates from policies.json
- (every policy markdown should just include the last updated date)
=> Fix: duplicate dates in privacy policy

src/components/organisms/AssetContent/index.tsx
Fixes #221
- remove pricing flow from AssetDetails for `thing` assets type
=> enhancement: remove price creation warning for "thing" type assets

src/components/atoms/Tabs.tsx, src/components/organisms/AssetActions/Compute/FormComputeDataset.tsx, src/components/pages/Profile/History/index.tsx
Fixes #222
- open profile page at the correct tab if specified in the url
- show the "edge ctd device not available" warning only for edge assets
=> fix: default tab selection in profile page

content/site.json
Fixes #230
Currently the link is broken, do not merge until the moveID portal is deployed
- add moveID portal as second entry in dropdown
=> enhancement: add moveID portal to ecosystem dropdown

gatsby-config.js
- restore webpack size plugin in gatsby config
=> fix: restore webpack size plugin

.github/CODEOWNERS, src/components/@shared/Price/PriceUnit.tsx, src/components/Asset/AssetActions/Compute/PriceOutput.tsx
- fix missing spacing between tokens on the asset detail page
- explicitly display prices equal to `0` instead of `free` for the asset detail page
=> feat: price output

src/components/Search/utils.ts
Fixes #344
- manually set `totalPages` and `totalResults` to 0 when getting no matches on a search
=> fix: wrong asset count for 0 results searches

src/@utils/compute.ts
=> fix: get compute algo list for assets with multiple trusted algo publishers

src/@utils/compute.ts
Fixes display of duplicate ctd jobs in all job histories, whenever multiple provider endpoints keep track of the same jobs
- add filter function to only show jobs from providers that are `service[0].serviceEndpoints` in the jobs input asset
=> fix: duplicate ctd jobs from multiple provider endpoints

src/@types/AssetExtended.d.ts, src/components/@shared/AssetList/index.tsx
Fixes a crash when switching to list view in catalogue page
Also removes outdated MetadataExtended type, as typings now are supported by ocean.js
=> Fix: catalogue list view crash

src/components/@shared/AssetList/index.tsx
- Add networks column whenever multiple `chainIds` are selected in `UserPreferences`
=> feat: add network column to list view

content/site.json, src/@context/MarketMetadata/_types.ts, src/components/@shared/MenuDropdown/index.tsx, src/components/Header/Menu.tsx, src/components/Home/Ecosystem/Card.tsx, src/components/Home/Ecosystem/index.tsx
- add new "isLive" indicator to menu item content
- update behavior of ecosystem homepage component
- remove live indicator
- remove button links
- update behavior of menu links, remove `isLive === false` entries
=> Feat: ecosystem update

package.json, src/@utils/dispenser.ts, src/@utils/nft.ts, src/components/Asset/Edit/EditComputeDataset.tsx, src/components/Asset/Edit/EditMetadata.tsx
Fixes failed edit transactions. 
- adds wait to edit transactions 
- replace unresponsive subgraph endpoint
=> fix: add wait to txs

package.json, src/@utils/dispenser.ts, src/components/Asset/Edit/EditComputeDataset.tsx, src/components/Asset/Edit/EditMetadata.tsx
* fix: add wait to txs
* fix: replace unresponsive subgraph endpoint
* feat: call wait after check if tx is defined
* refactor: remove early wait call
=> fix: edit transactions (#524) and replace unresponsive subgraph endpoint

src/@context/Asset.tsx, src/@hooks/useNftFactory.ts, src/components/Asset/Edit/EditComputeDataset.tsx, src/components/Asset/Edit/EditMetadata.tsx, src/components/Publish/index.tsx
- add autoWallet capabilities for publish flow
- add autoWallet to all edit functionalities
-
=> feat: auto wallet for publish and edit functionality

content/site.json
- Remove GEN-X deprecation text as it's outdated
- Add announcement about the load test on Pontus-X Devnet
=> docs: update announcement text (load testing)

src/components/@shared/Publisher/index.tsx
Fixes #
- shows the address instead of the name if the name is not available
=> fix: show address as provider if the address is not in pontusxAddresses.json

app.config.js, src/@context/MarketMetadata/_types.ts, src/components/Asset/AssetActions/ButtonBuy/index.tsx, src/components/Asset/AssetActions/Download/ContractingProvider/index.module.css, src/components/Asset/AssetActions/Download/ContractingProvider/index.tsx, src/components/Asset/AssetActions/Download/index.tsx, src/components/Asset/AssetActions/utils.ts
Fixes #
- go to service Button
=> fix: go to service Button

pontusxAddresses.json
Onboarding CapGemini Deutschland
Lei: 549300H01HLL4GPC1916
Public Address: 0x105Bf736Ae0Fc0Aefe3339498da149bb207890b9
“gx:countrySubdivisionCode”: “DE-BE”,
“gx:addressCountryCode”: “DE”,
“gx:streetAddress”: “Potsdamer Platz 5",
“gx:postalCode”: “10785",
“gx:locality”: “Berlin”
=> Onboarding CapGemini

app.config.js, src/components/Publish/_constants.tsx, src/components/Publish/_utils.ts
Fixes #
- update provider URL configuration and add allowed Gaia-X registry domains
=> refactor: replace hardcoded config points

pontusxAddresses.json
Inspirators! OÜ
Mäealuse tn 2/1,
Tallinn, 12618
Estonia
Public Address: 0x599Eb75866526822Df3fb32241506bDd3bA5F22E
Company Registration No.: 16224196, 
VatID: EE102369555,
Website: https://inspirators.eu/
=> Add Inspirators

src/components/Asset/AssetActions/Compute/FormComputeDataset.tsx, src/components/Asset/AssetActions/Compute/index.tsx, src/components/Asset/AssetActions/TermsAndConditionsCheckbox.tsx
when publishing a compute asset, the app crashed during the preview
- hand over the license as `prop` to `FormComputeDataset.tsx`
=> fix: license on compute publish preview

pontusxAddresses.json
Adding AllUnity Token - 0xE158265FD2be5BCc208621f2c0f8AfCF11aC8408
Onboarding Proalpha GmbH - 0x6e9d6595d216477dc57F966415Dd34d9585A0bc3
Proalpha GmbH
Auf dem Immel 8
67685 Weilerbach
Germany
Amtsgericht Kaiserslautern HRB 31613
VAT-ID: DE 291170635
LEI Code: 529900R6AJ2UOEIL7218
Public Address: 0x6e9d6595d216477dc57F966415Dd34d9585A0bc3
=> Onboarding Proalpha GmbH + Adding AllUnity Token
