deltaDAO/mvg-portal

- address.config.js
- content/pages/publish/form-algorithm.json
- content/pages/publish/form-dataset.json
- src/components/molecules/FormFields/Terms.tsx
- src/components/pages/Home.tsx
- src/hooks/useAddressConfig.ts
- src/utils/aquarius.ts
- add featured assets selection to front page
- fix terms and conditions checkbox on publish page
> Featured assets + terms fix

- src/components/organisms/HomeIntro.module.css
- src/components/organisms/HomeIntro.tsx
Fixes #10 
- header refactor to avoid using absolute positioning
> Header refactor

- content/pages/index/content.json
- content/pages/index/intro.json
Fixes #16 
- add content to intro.json
- add content to content.json
> Add content to frontpage

- src/components/atoms/Button.module.css
Fixes #13 
- add movement to the button to imitate "press" action on hover
> Enhancement: button hover animation

- chains.config.js
Fixes #12 
- remove Rinkeby chain id
- remove Ropsten chain id
> Enhancement(chains): remove rinkeby and ropsten

- src/components/templates/Page.tsx
Fixes #18 
- show "powered" by section only on home page
> Fix: page header

- content/pages/index/intro.json
- Change title and cta target of intro section on frontpage
> Hotfix: Add Academy to frontpage

- src/components/organisms/AssetActions/Compute/index.tsx
- src/components/pages/Profile/History/ComputeJobs/Results.tsx
Fixes #40 
- Update error message for transaction failure on service consumption
> Fix: Service Consumption Error

- src/providers/Web3.tsx
Fixes #39 
- The results modal window now correctly closes only on user input
> Fix: details modal window

- content/site.json
Fixes #37 
Adjust text content for main build
- change text in announcement banner
- change text in footer
> Update Announcement Banner & Footer

- src/components/atoms/ButtonBuy.module.css
- src/components/atoms/ButtonBuy.tsx
- src/components/organisms/AssetActions/Compute/FormComputeDataset.tsx
- src/components/organisms/AssetActions/Compute/index.tsx
- add warning for un-whitelisted wallets before ctd purchase
- new error message in case of ctd start failure
> Enhancement: Improve Error Message

- content/pages/privacy/policies.json
- update the policy date for the english policy
> Hotfix: update en policy date

- src/components/molecules/UserPreferences/Networks/index.tsx
- src/hooks/useNetworkMetadata.ts
- src/utils/web3.ts
Fixes #69 
See [https://github.com/oceanprotocol/market/commit/b2330fdc99c847afb5065223f49d9d2dc8e610d1](https://github.com/oceanprotocol/market/commit/b2330fdc99c847afb5065223f49d9d2dc8e610d1)
> Fix: update network metadata

- content/pages/edit.json
- content/pages/publish/form-algorithm.json
- content/pages/publish/form-dataset.json
- src/components/organisms/AssetContent/MetaFull.tsx
- src/components/pages/Publish/FormPublish.tsx
- remove author field from publish / edit forms
- autmatically set author field value = siteTitle during publish
- remove author from asset details page
> Feat: remove author field

- content/pages/edit.json
- content/pages/publish/form-algorithm.json
- content/pages/publish/form-dataset.json
- src/components/organisms/AssetContent/MetaFull.tsx
- src/components/pages/Publish/FormPublish.tsx
- remove the author field from publish / edit forms
- automatically set author field value = siteTitle
- remove author from asset details
> Hotfix: remove author field

- content/pages/publish/form-algorithm.json
- content/pages/publish/form-dataset.json
- content/pages/publish/index.json
- content/price.json
- src/components/atoms/Input/InputElement.tsx
- src/components/organisms/Footer.tsx
- src/components/pages/Publish/FormAlgoPublish.tsx
Fixes #88 
- remove terms page
- remove terms and conditions checkbox on publish forms
- remove terms and conditions links in content
> Feat: remove terms

- src/components/molecules/SearchBar.module.css
- src/components/molecules/SearchBar.tsx
> fix: search bar width for desktop view

- src/components/atoms/VerifiedPublisher.module.css
- src/components/atoms/VerifiedPublisher.tsx
- src/components/pages/Profile/History/PublishedList.tsx
- src/components/pages/Profile/index.tsx
- src/pages/profile/index.tsx
> Feat: verified publisher

- src/components/pages/Profile/Header/Stats.tsx
> feat: hide liquidity info in profile

- src/utils/metadata.ts
- correctly parse the raw service SD to extract the verified provider name
> fix: correctly set provider name from raw SD

- content/site.json
Fixes #161
- remove onboarding portal link from the ecosystem menu
> fix: remove onboarding portal link

- app.config.js
- Update compliance-service api version
> fix: update compliance service uri

- src/components/atoms/Loader.module.css
- src/components/atoms/Loader.tsx
- src/components/molecules/AssetTeaser.tsx
- src/components/organisms/AssetList.tsx
- src/providers/Asset.tsx
Fixes #165 
- add gradient style to loader component
- allow AssetTeaser to display unpriced assets
- move price loading out of `loading` scope for asset provider
Could think about introducing smth like https://github.com/danilowoz/react-content-loader to improve the look of the loading status.
> Enhancement: Improve Loading Speed

- address.config.js
I would like to include EuProGigant #319 as most updated asset, the Fuji-Set as it is related to open science and the PEAQ dataset with charging stations to fill the last section of the landing page.
> Update landing page

- src/components/organisms/AssetContent/index.tsx
See https://github.com/deltaDAO/portal-euprogigant/pull/41
> fix: asset details not showing for publisher

- src/components/molecules/WalletNetworkSwitcher.tsx
- src/components/molecules/Web3Feedback.tsx
- src/components/pages/Publish/FormActions.tsx
- src/components/templates/PageAssetDetails.tsx
- src/providers/Asset.tsx
- src/providers/Web3.tsx
Fixes #148
- disable publish when user is not connected to correct chainId
- update metadata feedback and web3 switcher accordingly
- disable asset details page if not from a supported network
> feat: only allow chainid of 2021000 n the portal

- content/pages/publish/form-dataset.json
Fixes #
increase the specificity of our disclaimers
> feat: update publishing disclaimers

- content/pages/publish/form-algorithm.json
Fixes #
increase the specificity of our disclaimers
> feat: update algorithm publishing disclaimer

- content/assetDisclaimer.json
- content/pages/publish/form-algorithm.json
- content/pages/publish/form-dataset.json
- src/@types/MetaData.d.ts
- src/components/atoms/ButtonBuy.module.css
- src/components/atoms/ButtonBuy.tsx
- src/components/atoms/Input/InputElement.module.css
- src/components/atoms/Input/InputElement.tsx
- src/components/molecules/FormFields/Terms.tsx
- src/components/pages/Publish/index.tsx
- src/models/FormAlgoPublish.ts
- src/models/FormPublish.ts
- src/utils/metadata.ts
Fixes #177
- add checkboxes before publish
- add disclaimer under asset buy button
> feat: increase transparency using checkboxes disclaimers

- src/components/templates/Search/utils.ts
- src/utils/aquarius.ts
Fixes #183
- exclude "thing" type assets from query results
> feat: exclude "thing" type assets from query results

- src/providers/Asset.tsx
> fix: display assets when account is not connected

- content/pages/publish/form-algorithm.json
- content/pages/publish/form-dataset.json
- src/@types/Form.d.ts
- src/@types/MetaData.d.ts
- src/components/atoms/Alert.module.css
- src/components/atoms/ButtonBuy.tsx
- src/components/atoms/Input/Disclaimer.tsx
- src/components/organisms/AssetActions/Compute/index.module.css
- src/components/organisms/AssetActions/Compute/index.tsx
- src/components/organisms/AssetActions/Consume.module.css
- src/components/organisms/AssetActions/Consume.tsx
- src/components/organisms/AssetActions/Pool/Add/index.tsx
- src/components/organisms/AssetActions/Trade/FormTrade.tsx
- src/components/organisms/AssetActions/index.tsx
- src/components/organisms/AssetContent/Pricing/index.tsx
- src/components/pages/Publish/FormActions.module.css
- src/components/pages/Publish/FormActions.tsx
- src/components/pages/Publish/FormAlgoPublish.tsx
- src/components/pages/Publish/FormPublish.tsx
- src/components/pages/Publish/index.tsx
- src/components/pages/Verify/index.tsx
- src/models/Asset.ts
- src/models/FormAlgoPublish.ts
- src/models/FormPublish.ts
- src/providers/Asset.tsx
- src/utils/metadata.ts
- tests/unit/__fixtures__/testFormData.ts
Fixes #188
- transform "wallet address" checkbox to disclaimer
- update "Metadata confirmation" checkbox title
> enhancement: replace wallet address checkbox with disclaimer

- src/components/organisms/AssetActions/Compute/index.tsx
- src/components/pages/Home.tsx
- src/components/templates/Search/utils.ts
- src/utils/aquarius.ts
Fixes #192 
- change aqua query to `_id` instead of `id`
-
-
> Fix: aquarius id queries

- content/pages/privacy/en.md
Fixes #
updated contact details
> update contact details

- src/components/molecules/FormFields/FilesInput/index.tsx
- src/providers/UrqlProvider.tsx
- update urql provider to initialize with 2021000 chainId
- update fallback chainId to file info check to 2021000
> hotfix: update default urql provider config chainId

- chains.config.js
- src/utils/ocean.ts
- instead of hardcoding the overwrite of metadatacache move this to the `chains.config.js` file
> Enhancement: move metdatacacheuri to chains config

- src/components/organisms/Footer/index.module.css
> fix: footer padding

- src/components/organisms/AssetActions/Compute/FormComputeDataset.tsx
- src/providers/Web3.tsx
Fixes #225
- make the buy button available if a user connects after selecting an algorithm for ctd (if the conditions are met)
> fix: button buy disabled status

- src/components/pages/Profile/History/ComputeJobs/index.tsx
Fixes #220
- fix ctd details modal autoclose
> fix: ctd details modal auto closing without user input

- README.md
- content/site.json
- package.json
- src/components/atoms/Seo.tsx
Fixes #232 
- update site title and tab template
- update readme title
- update package.json description
> enhancement: update portal title

- app.config.js
Fixes https://github.com/deltaDAO/multi-repo-issues/issues/4
- update compliance API uri
> feat: update compliance api uri

- content/pages/publish/form-dataset.json
- src/components/molecules/FormFields/ServiceSelfDescription.tsx
- remove raw self-description option in publish
> feat: remove raw self-description option in publish

- app.config.js
- src/components/atoms/VerifiedBadge.module.css
- src/components/atoms/VerifiedBadge.tsx
- src/components/molecules/FormFields/FilesInput/index.tsx
- src/components/molecules/FormFields/ServiceSelfDescription.module.css
- src/components/molecules/FormFields/ServiceSelfDescription.tsx
- src/components/organisms/AssetContent/MetaMain.tsx
- src/components/organisms/AssetContent/index.tsx
- src/components/pages/Verify/Visualizer.tsx
- src/components/pages/Verify/index.tsx
- src/hooks/useSiteMetadata.ts
- src/providers/Asset.tsx
- src/utils/metadata.ts
- add support for 2204 and 2206 SD shapes
- store raw serviceSDs in gx storing service
> feat: add sd storage service

- src/components/organisms/AssetContent/MetaMain.tsx
- src/utils/metadata.ts
- skip participant verification for 22.04 service SDs
- fix asset publisher display
> enhancement: skip participant verification for 22.04 service SDs

- src/components/atoms/Copy.module.css
- src/components/atoms/Copy.tsx
- src/components/organisms/AssetContent/index.module.css
- src/components/organisms/AssetContent/index.tsx
- src/components/pages/Verify/Visualizer.module.css
- src/components/pages/Verify/Visualizer.tsx
- src/components/pages/Verify/index.tsx
- add option to copy the service self-description content to the clipboard
> feat: copy self-description to clipboard

- README.md
- content/pages/index/content.json
- content/promotionBanners.json
- src/components/molecules/PageHeader.module.css
- src/components/molecules/PageHeader.tsx
- replace MVG and minimal viable Gaia-X instances with the new Pontus-X - Gaia-X Web3 Ecosystem branding
> enhancement: rebrand MVG to Pontus-X

- chains.config.js
- src/components/atoms/Publisher/index.tsx
- src/components/molecules/WalletNetworkSwitcher.tsx
- src/components/molecules/Web3Feedback.tsx
- src/providers/UserPreferences.tsx
- update default chainId selection
- remove localstorage check during chainId selection initialization
- remove 3box profile broken integration
- fix wallet network switcher target network
> enhancement: update networks default pre-selection

- content/site.json
- remove statistics page link
- update block explorer link
> enhancement: update footer external links

- content/site.json
> enhancement: update footer content

- address.config.js
> Update Portal Assets

- src/pages/asset/index.tsx
- check if the did param is a valid eth address and navigate to checksum version
> feat: add checksum check for DIDs in /asset

- src/utils/metadata.ts
- skip participantSD check when verifying self-descriptions
> fix: temporary disable verifyParticipant

- apollo.config.js
- codegen.yml
- src/utils/ocean.ts
> fix: subgraph url

- content/pages/imprint.md
> refactor: imprint

- app.config.js
- chains.config.js
- genxAddress.json
- networksMetadata.config.js
- package.json
- scripts/copy-addresses.js
- scripts/write-networks-metadata.js
- src/@hooks/useNetworkMetadata/utils.ts
- src/@utils/aquarius/index.test.ts
- src/@utils/aquarius/index.ts
- src/@utils/ocean.ts
> feat: add GEN-X Testnet

- content/site.json
Added the OVAL Portal to Ecosystem menu
> Added OVAL Portal to Ecosystems

- app.config.js
- content/pages/edit.json
- content/pages/publish/form-dataset.json
- src/components/molecules/FormFields/ServiceSelfDescription.tsx
- src/utils/metadata.ts
- update compliance API url
- remove raw SD support
> fix: compliance API verification flow

- app.config.js
- src/@context/Asset.tsx
- src/components/Publish/_utils.ts
- update compliance api check to utilize the new `credential-offer` endpoint
- update publisher name check from SD
> feat: update compliance api check

- package-lock.json
- src/@context/Profile/index.tsx
Fixes #325 
- fix published assets profile stats
> fix: profile crashes for certain accounts

- package-lock.json
- src/components/Profile/History/ComputeJobs/index.tsx
> fix: refetch ctd history on page change

- content/site.json
- src/@utils/docker.ts
- update dockerhub proxy url to `https://dockerhub-proxy.delta-dao.com`
- remove faucet link from footer
> feat: update dockerhub proxy

- src/@utils/aquarius/index.ts
- src/@utils/assetConvertor.ts
- src/@utils/compute.ts
- src/@utils/ddo.ts
- src/components/@shared/FormInput/InputElement/AssetSelection/index.test.tsx
- src/components/@shared/FormInput/InputElement/AssetSelection/index.tsx
- src/components/@shared/FormInput/index.test.tsx
- src/components/@shared/VerifiedBadge/index.module.css
- src/components/@shared/VerifiedBadge/index.tsx
- src/components/Asset/AssetActions/Compute/AlgorithmDatasetsListForCompute.tsx
- src/components/Asset/AssetActions/Compute/FormComputeDataset.tsx
- src/components/Asset/AssetActions/Compute/History.module.css
- src/components/Asset/AssetActions/Compute/WhitelistIndicator.module.css
- src/components/Asset/AssetActions/Compute/WhitelistIndicator.tsx
- src/components/Asset/AssetActions/Compute/index.tsx
- src/components/Asset/AssetActions/Download.module.css
- src/components/Asset/AssetActions/Download.tsx
- src/components/Asset/AssetActions/index.module.css
- src/components/Asset/AssetActions/index.tsx
- src/components/Asset/Edit/FormEditComputeDataset.tsx
- add address whitelist badge to asset actions
- disable non whitelisted algos in the compute asset selection form
> feat: address whitelist indicator

- chains.config.js
- content/site.json
- networksMetadata.config.js
- package.json
- src/components/@shared/AddNetwork/index.module.css
- src/components/@shared/AddNetwork/index.tsx
- src/components/@shared/WalletNetworkSwitcher/index.tsx
- src/components/Header/Menu.module.css
- src/components/Header/Menu.tsx
- src/components/Header/UserPreferences/index.tsx
- src/components/Header/Wallet/Details.module.css
- src/components/Header/Wallet/Details.tsx
Fixes #314 
- update ecosystem links
- update explorer links
- add GEN-X Testnet button under account dropdown
- move "debug" and "external content consent" preference options to separate menu
> feat: update ecosystem links

- package-lock.json
- src/components/Profile/History/index.tsx
- src/pages/profile/index.tsx
Fixes https://github.com/deltaDAO/mvg-portal/pull/415#discussion_r1322589571
- re-enable `defaultTab` URL param at `/profile` and `/profile/[address]`
> feat: get profile defaultTab from url params

- src/components/Publish/_utils.ts
- correctly show asset publisher name from service credential
> fix: asset publisher name

- app.config.js
- content/site.json
- src/@context/MarketMetadata/_types.ts
- src/components/App/index.tsx
- add alert banner for portal preview deployment
> feat: add dev preview banner

- content/pages/privacy/en.md
- content/pages/startComputeDataset.json
- content/pages/terms.md
- content/publish/form.json
- src/components/@shared/FormInput/InputElement/Radio/Option.module.css
- src/components/@shared/FormInput/InputElement/Radio/Option.tsx
- src/components/@shared/FormInput/InputElement/Radio/index.tsx
- src/components/@shared/FormInput/InputElement/index.tsx
- src/components/@shared/FormInput/index.tsx
- src/components/Asset/AssetActions/Compute/FormComputeDataset.module.css
- src/components/Asset/AssetActions/Compute/FormComputeDataset.tsx
- src/components/Asset/AssetActions/Compute/_constants.ts
- src/components/Asset/AssetActions/Compute/index.tsx
- src/components/Publish/Metadata/index.module.css
- src/components/Publish/Metadata/index.tsx
- src/components/Publish/Pricing/Fees.tsx
- src/pages/[slug].tsx
- add "terms and condition" checkbox to c2d form
- automatically generate `/terms` table of content
> feat: c2d terms conditions checkbox

- filters.config.js
> enhancement: temporary remove "categories" filter type

- chains.config.js
- package-lock.json
> feat: update default provider

- content/pages/home/content.json
- content/site.json
- src/@utils/wallet/chains.ts
- src/components/App/index.tsx
- use dynamic title and URL in the dev preview warning banner
> enhancement: dev preview warning

- content/site.json
> feat: update site title

- content/site.json
> feat: update site tagline

- src/components/@shared/FormInput/InputElement/Provider/index.tsx
- src/components/@shared/FormInput/index.tsx
- src/components/Publish/_constants.tsx
Fixes #
- fix custom provider error handling on publish form
- update default provider when user is disconnected
> fix: default provider

- src/components/Asset/AssetActions/Compute/FormComputeDataset.tsx
- only pre-select algo in c2d form if user is allowed to consume
> fix: ctd algo pre-selection 

- src/components/Asset/AssetActions/Compute/FormComputeDataset.tsx
- fix: avoid ctd algo pre-selection if user is not allowed to consume
> fix: ctd algo pre-selection  (#467)

- content/site.json
> enhancement: update tagline

- src/components/Asset/AssetActions/Download/index.tsx
> feat: update saas success access message

- src/@utils/aquarius/index.test.ts
- src/@utils/aquarius/index.ts
- src/components/Asset/RelatedAssets/_utils.ts
* fix: related assets query
* fix: test
> fix: search query (#480)

- src/@utils/aquarius/index.test.ts
- src/@utils/aquarius/index.ts
> fix: query with whitelist address addition

- package-lock.json
> fix: tests

- address.config.js
Adding 0x28080F654eED6CC00e8b16F4841E92CD0c2C0778 as deltaDAO Demo account.
> Include deltaDAO Demo Address

- chains.config.js
- networksMetadata.config.js
- update explorer url for ponrus-x paratime
> Update pontus-x explorer url

- src/@utils/subgraph.ts
- adds wrapped EUROe address for Pontus-X
> feat: add wrapped euroe address

- content/pages/editMetadata.json
- src/components/Asset/Edit/EditMetadata.tsx
> fix: add checks if edit state tx was successful

- content/pages/editMetadata.json
- src/components/Asset/Edit/EditMetadata.tsx
Fixes asset state editing failed tx.
> fix: add checks if edit state tx was successful (#526)

- content/site.json
> Remove CIX

- pontusxAddresses.json
> Add Beia Consult International

- pontusxAddresses.json
> Onboard Anasoft

- content/site.json
- src/components/@shared/AnnouncementBanner/index.module.css
- src/components/@shared/AssetList/index.tsx
- src/components/App/index.tsx
- add an announcement to deprecate genx
> feat: add gen-x deprecation announcement

- pontusxAddresses.json
Onboarding of ZERTIFIER SL - 0xb993dfC7cAf2477770e60E1Ae6188F6147BDA92d
Company name: ZERTIFIER SL
LEI Code: 959800RQWU33YF7PA715
Company Register No.: RA000533 , GI-69603-8
Address: Terri 13, 17844-Cornellà de Terri, Spain, ES-13
> Onboarding - ZERTIFIER - 0xb993dfC7cAf2477770e60E1Ae6188F6147BDA92d

- src/@utils/wallet/index.ts
- src/components/@shared/AssetTeaser/index.tsx
- src/components/@shared/Publisher/index.tsx
- src/components/Asset/AssetContent/MetaMain/MetaAsset.tsx
- the names are now displayed in the asset header and in the asset teaser instead of the address
> feat: resolved address to display name

- src/components/Footer/Footer.module.css
Fixes #
- Footer logo subtitle made responsive
> fix: update footer subtitle width

- content/site.json
- src/components/@shared/FormInput/InputElement/ConsumerParameters/_validation.ts
- src/components/@shared/Page/PageHeader.tsx
- src/components/Footer/Links.tsx
- src/stylesGlobal/_variables.css
Fixes #
- deleted min validation from Parameter Name  
- rename footer section Privacy to Legal
- rename link Privacy to Privacy Policy
> fix: footer section & form validation

- src/@utils/aquarius/index.ts
Fixes #637 
- Update generatedQuery
> fix: update generatedQuery

- pontusxAddresses.json
Adding 0xB64d95B85FcbDb868AaF0075B023E36f374Bc4F7 for DFKI
> Add DFKI address 0xB64d95B85FcbDb868AaF0075B023E36f374Bc4F7

- src/components/Publish/_utils.ts
Updates fallback url for terms.
> fix: use correct terms link as fallback

- src/@context/Asset.tsx
- src/components/@shared/VerifiedBadge/index.module.css
- src/components/@shared/VerifiedBadge/index.tsx
- src/components/Asset/AssetContent/MetaMain/index.tsx
- src/components/Publish/_utils.ts
Fixes #618 
- compare service offering credential id with gx:dependsOn to filter out the correct ID
- add new state 'warning' to inform you when gx:dependsOn does not exist
> feat: check credential ID match warning

- src/components/@shared/Page/Seo/index.tsx
Update hostname used to create seo meta tags
> fix: update seo meta tags

- pontusxAddresses.json
Onboarding Leitat (Acondicionamiento Tarrasense)
VAT: ESG08360232
Public Address: 0x2912106B140669e5038A0cf768a4BDB202D67604
“gx:countrySubdivisionCode”: “ES-B”,
“gx:addressCountryCode”: “ES”,
“gx:streetAddress”: “De la Innovació, 2",
“gx:postalCode”: “08225",
“gx:locality”: “Terrassa”
Fixes #
-
-
-
> Onboarding Leitat

- src/components/Asset/AssetActions/Download/index.tsx
- update the purchase success message on payment mode Subscription
> fix: update purchase success message based on payment mode

- src/@utils/aquarius/index.test.ts
- src/components/@shared/Publisher/index.tsx
> fix: update tests

- .github/workflows/ci.yml
Fixes #
- update upload-artifact action to version 4
> chore: update upload-artifact action to version 4

- src/components/Header/UserPreferences/index.tsx
> fix: conditionally render AutomationWalletMode based on appConfig

- content/pages/startComputeDataset.json
- content/pages/startDownloadDataset.json
- src/components/Asset/AssetActions/Compute/FormComputeDataset.tsx
- src/components/Asset/AssetActions/Download/index.tsx
- src/components/Asset/AssetActions/TermsAndConditionsCheckbox.tsx
> fix: update asset terms and conditions wording and handling in forms

- app.config.js
Fixes #
- update compliance URI to point to the deltaDAO clearing house
> fix: update compliance URI to point to the deltaDAO clearing house

- src/@hooks/useAddressConfig.ts
- src/components/@shared/FormInput/InputElement/Credential/index.tsx
Fixes #
- display verified address names in Credentials component
-
-
> feat: display verified address names in Credentials component

- content/onboarding/index.json
- src/@images/x-cross.svg
- src/components/@shared/Onboarding/Header.module.css
- src/components/@shared/Onboarding/Header.tsx
- src/components/@shared/Onboarding/HideButton.module.css
- src/components/@shared/Onboarding/HideButton.tsx
- src/components/@shared/Onboarding/index.tsx
Fixes #
- add button to hide onboarding guide
-
-
> feat: add Hide button to Onboarding header

- src/components/@shared/ExplorerLink/ExplorerTokenLink.tsx
- src/components/Asset/AssetContent/MetaMain/MetaAsset.tsx
- src/components/Asset/AssetContent/MetaMain/index.tsx
- src/components/Asset/AssetContent/Nft/NftTooltip.tsx
- src/components/Asset/AssetContent/Nft/index.tsx
- create dedicated component for explorer token links
> refactor: dedicated component for explorer token links

- src/components/Publish/_utils.ts
> fix: ensure credentialSubject is accessed correctly

- src/components/@shared/FormInput/InputElement/Radio/index.module.css
- src/stylesGlobal/_variables.css
Fixes #
- made the checkbox border color slightly darker to improve visibility
> fix: checkbox border color

- app.config.js
> fix: remove default provider URL in app.config.js

- src/components/Publish/Preview/index.tsx
> fix: update price calculation for free pricing option in Preview 

- src/components/Publish/_utils.ts
> fix: rename parameter did to assetDid in verifyRawServiceCredential 

- pontusxAddresses.json
> Add Magnetic Torquer Service

- pontusxAddresses.json
Adding neusta production address.
> Adding Production Addresses

- src/components/Asset/AssetContent/EditHistory.tsx
- src/components/Asset/AssetContent/MetaMain/MetaInfo.module.css
- src/components/Asset/AssetContent/MetaMain/MetaInfo.tsx
- src/components/Asset/AssetContent/index.tsx
> fix: styling from publisher on MetaInfo

- content/pages/privacy/en.md
- content/pages/privacy/policies.json
Fixes #
- update privacy policy
> chore: update privacy policy

- src/components/@shared/FormInput/InputElement/AssetSelection/index.tsx
> fix: adjust asset selection component to enable selection on edit page

- .github/CODEOWNERS
- update codeowners file to include subdirectories for content updates
see: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file
> chore: update codeowners 

- src/@utils/wallet/index.ts
> feat: add custom provider instead of publicProvider

- app.config.js
- src/components/@shared/Page/Seo/index.tsx
- src/pages/_app.tsx
> Feat/use next/script on plausible

- .jest/__mocks__/hooksMocks.ts
- app.config.js
- src/@utils/wallet/index.ts
- src/components/@shared/FormInput/InputElement/AssetSelection/index.tsx
- src/components/@shared/Page/Seo/index.tsx
- src/pages/_app.tsx
> Development to Main

- src/components/Asset/AssetActions/Compute/index.tsx
> feat: remove ocean from pricelist

- content/pages/privacy/policies.json
> fix: rollback privacy policy date to 2025-03-04

- content/pages/cookies/en.md
> fix: improve clarity in cookie policy documentation

- src/@constants/errors.ts
- src/@utils/provider.ts
- src/stylesGlobal/_toast.css
Fixes #
- enhance error message for algorithm checksum mismatch
> fix: enhance error message for algorithm checksum mismatch

- src/components/Profile/Header/Account.tsx
Fixes #
- Address names are now recognized in the Account component regardless of the capitalization of the address
> fix: refactor address key retrieval for verified addresses in Account component

- pontusxAddresses.json
Onboarding IDEKO S. Coop.
0x28553327C3e469a2De5D53faaE2d27C0c0Fa4d1b
Ideko S.Coop.
Polígono Industrial Arriaga nº2
Elgoibar - Gipuzkoa
Spain
Tlf : 943748000
CIF: F20147773
> Onboarding - IDEKO S. Coop. - 0x28553327C3e469a2De5D53faaE2d27C0c0Fa4d1b

- content/site.json
- src/@context/MarketMetadata/_types.ts
- src/components/@shared/AnnouncementBanner/index.module.css
- src/components/@shared/Markdown/index.tsx
- src/components/App/index.tsx
- src/stylesGlobal/_colors.css
Fixes #
- add announcement for Pontus-X onboarding survey
- enhance link handling in Markdown component to open external links in new tab
> feat: add announcement for Pontus-X onboarding survey

- content/pages/privacy/en.md
- content/pages/privacy/policies.json
Fixes #
- update privacy policy
- update privacy policy date
> feat: update privacy policy & privacy policy date

- pontusxAddresses.json
Onboarding NOUMENA Digital AG
Public Address: 0xE30DD32904E5c3D7f35D5324E638c45916143b20
Noumena Digital AG
Bahnhofstrasse 22
6300 Zug
Switzerland
Commercial Register Office of the Canton of Zug, CHE-289.789.695 VAT ID: 289.789.695
> Onboarding NOUMENA - 0xE30DD32904E5c3D7f35D5324E638c45916143b20

- pontusxAddresses.json
Onboarding
JDS GmbH
Strandstraße 87
18055 Rostock
Germany
Public address: 0x7bbceba47d20d657b2a706329c0617262d5a2e17
VAT ID: DE449793121
DUNS: 316419384
Company Register: HRB 16767
> Onboarding JDS GmbH

- pontusxAddresses.json
Galicia Supercomputing Center (CESGA)
Avenida de Vigo, s/n Campus Vida
15705 Santiago de Compostela
Spain
Website: http://www.cesga.gal
Public Address: 0xb0747287c71Bc3d376531856b6d346697A3DD233
VAT ID: ESG15852981
CIF: G-15852981
> Onboarding CESGA - 0xb0747287c71Bc3d376531856b6d346697A3DD233

- src/components/Asset/AssetActions/ConsumerParameters/FormConsumerParameters.tsx
Fixes #
- enhance FormConsumerParameters to manage state and handle input changes
> feat: enhance FormConsumerParameters to manage state and handle input changes

- pontusxAddresses.json
Onboarding 
FIDES Labs B.V.
Vredenburg 40
3511BD Utrecht
Netherlands
KVK / Company Registration Number: 97159174
VAT number: NL867933604B01
Public Address: 0xA17F074dB2785b84D96153c42822002A26b98c34
> Onboarding FIDES Labs B.V. - 0xA17F074dB2785b84D96153c42822002A26b98c34

- pontusxAddresses.json
Politecnico di Milano, https://compliance.agrospai.udl.cat/.well-known/POLIMI.vp.json
Josephinum Research, https://compliance.agrospai.udl.cat/.well-known/JR.vp.json
> Onboarding POLIMI and JR

- pontusxAddresses.json
> Adding AllUnity Deployer

- pontusxAddresses.json
Adding Kiel Parking Data Address
> Adding Kiel Parking

- src/components/Asset/AssetActions/Compute/FormComputeDataset.tsx
- src/components/Asset/AssetActions/Compute/index.tsx
- src/components/Asset/AssetActions/ConsumerParameters/FormConsumerParameters.tsx
Fixes #752
- use formik state instead of useState
- revert memorized parameters workaround
> Fix consumer parameter reset

- networksMetadata.config.js
> config: update EURAU decimals from 18 to 6
